webcomics/dosage

doc/README.txt

README had the old URL, I propose fixing it.

fix URL in README.txt

---

dosagelib/plugins/r.py

Added "Ralf the Destroyer" comic

Added "Ralf the Destroyer"

---

dosagelib/plugins/o.py
dosagelib/plugins/s.py

- Shermans Lagoon and 
- On The Fastrack working again
- Corrected name of "On the Fastrack"

Corrections for two comics

---

dosagelib/plugins/r.py

Small fix to successfully scrape all 'Ruthe' strips again.

Fixed 'Ruthe'

---

dosagelib/util.py

Modified maximum page size

---

dosagelib/plugins/s.py

Changed to https on April 1, 2016.

Fix Sherman's Lagoon

---

dosagelib/plugins/p.py
dosagelib/plugins/s.py

Some new comics:
-Space Junk Arlia
-Prince of Sartar

New comics

---

dosagelib/plugins/gocomics.py

GoComics no longer has nav on the comic's home page. (Fixes #108)

---

dosagelib/plugins/l.py

Site uses a WordPress build, but does not explicitly match any existing scrapers.

Update for new LookingForGroup site format

---

README.md

I made a couple of small grammar and spelling changes.

minor spelling and grammar errors

---

dosagelib/plugins/t.py

Added Support for the webcomic Tripping Over You

Added support for Tripping Over You comic

---

dosagelib/plugins/g.py

Domain name and URLs have changed slightly.
Fixes #105.

Fix Girls with Slingshots matchers

---

dosagelib/plugins/t.py

New comic: The Rock Cocks

---

dosagelib/rss.py
tests/mocks/dailydose.rss
tests/test_rss.py

Also added a very basic test for feed parsing.
I haven't written any serious Python for ages, so sorry if it's not particularly excellent.

Fix missing returns in RSS parsing

---

dosagelib/plugins/o.py

Hi, 
I've fixed the tags for oglaf
It should be working as intended now 
Thanks,
hkocharyan

fixed oglaf next and previous tags

---

dosagelib/plugins/comicskingdom.py
scripts/comicskingdom.py
scripts/generate_json.sh
scripts/update_plugins.sh

Note that going back more than about seven days is a paid feature and is untested.

Add ComicsKingdom.com (aka King Features)

---

dosagelib/plugins/h.py

This pull request will add support for the comic Headless Bliss, using the ComicControlScraper module.

Added Headless Bliss

---

dosagelib/plugins/h.py
dosagelib/plugins/u.py

This pull request will add support for the comic [un]Divine (unDivine), using the ComicControlScraper module.

Added unDivine

---

dosagelib/plugins/webtoons.py

Added the following to the webtoons plugin:
- FisheyePlacebo
- ScoobandShag
- ZomCom

Added FisheyePlacebo, ScoobandShag, ZomCom

---

dosagelib/plugins/webtoons.py

Added Comic Webtoons/Punderworld

Added Comic Punderworld

---

dosagelib/plugins/comicfury.py

Added _Dragons and Silk_ and _View Hub_ from ComicFury.
(The webtoon engine is greatly appreciated by the way! Many thanks to you and Daniel.)

Added two ComicFury comics

---

dosagelib/plugins/b.py
dosagelib/plugins/comicfury.py
dosagelib/plugins/i.py
dosagelib/plugins/l.py
dosagelib/plugins/old.py
dosagelib/plugins/smackjeeves.py
dosagelib/plugins/w.py

- Add WintersLight
- Add LazJonesAndTheMayfieldRegulators
- Fix GrowingTroubles (migrated to ComicFury)
- Fix filenames for IslaAukate (removes a new cache-busting postfix)
- Fix Bethellium navigation (#156)

Add two comics, fix three others

---

dosagelib/plugins/d.py
dosagelib/plugins/g.py
dosagelib/plugins/n.py
dosagelib/plugins/p.py
dosagelib/plugins/s.py
dosagelib/plugins/t.py

Need to add some of my favorites!
DaughterOfTheLilies, SaffronAndSage, ParaNatural, GuildedAge, NeverSatisfied, SisterClaire, TheForgottenOrder, TheBoyWhoFell, TheGlassScientists

Add 9 new comics

---

dosagelib/plugins/mangadex.py
dosagelib/plugins/smackjeeves.py
dosagelib/plugins/webtoons.py

Add BloopBloopRelationshipComic to Webtoons

Add BloopBloopRelationshipComic

---

dosagelib/plugins/n.py
dosagelib/plugins/r.py

Fix for Ruthe.de and NichtLustig.de (now joscha.com)

---

doc/adding_new_comics.md

url format was a bit inconsistent. note that I am _NOT_ experienced with this so please correct the PR if it is incorrect

consistency

---

dosagelib/plugins/b.py

This adds the comic Beach WZRD

Added BeachWZRD

---

.gitignore
dosagelib/plugins/comicfury.py
dosagelib/plugins/comicskingdom.py
dosagelib/plugins/gocomics.py
dosagelib/plugins/old.py
dosagelib/plugins/webtoons.py
pyproject.toml
setup.cfg
tox.ini

Additionally, this adds some hackery to let flake8 read its config from pyproject.toml.

Update flake8 & plugins

---

dosagelib/plugins/webtoons.py

Add the Aces-Wild comic (https://www.webtoons.com/en/challenge/aces-wild/list?title_no=689025)

Add AcesWild (Webtoons)

---

dosagelib/plugins/l.py

Update LookingForGroup (fixes #254)

---

dosagelib/plugins/l.py

Update LeastICouldDo (fixes #257)

---

dosagelib/plugins/a.py

add the class for AwkwardZombie using the basic parser
https://www.awkwardzombie.com/

Add AwkwardZombie

---

dosagelib/plugins/comicskingdom.py
pyproject.toml

See https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy

Modernize importlib.resources usage

---

dosagelib/plugins/c.py

Add CassiopeiaQuinn from https://www.cassiopeiaquinn.com/

Add CassiopeiaQuinn

---

dosagelib/plugins/webtoons.py

From here https://www.webtoons.com/en/canvas/alloy-comics/list?title_no=747447
Thank you,

Added Alloy Comics to the WebToons modules

---

dosagelib/plugins/webtoons.py

[Dungeons & Doodles: Tales From the Tables](https://www.webtoons.com/en/canvas/dungeons-doodles-tales-from-the-tables/list?title_no=682646).
Hopefully, this should work.

feat(webtoons): added dungeon & doodles, Tales From The Table

---

dosagelib/plugins/webtoons.py

https://www.webtoons.com/en/canvas/hench/list?title_no=857225
Desi ( Short for Despair) is a henchmen for the evil dark lord Ivel. It's always been her dream to become the most cruel, violent, and evil lackey one could ever hope for. The only problem is that they can't seem to do anything right! When even the hero takes pity on you, what is a henchman supposed to do? UPDATES EVERY OTHER THURSDAY

feat(webtoon): added hench comics
